import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/profile.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";


export default function Home() {
  return (
    <>
      <Head>
        <title>Satyendu Shukla</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilePic} alt="Satyendu" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design"
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a passionate in data science and front-end development, I
                bring ideas to life through innovative web applications and
                data-driven solutions. Explore my projects and articles,
                showcasing my expertise in React.js, data science, and modern
                web development techniques.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link href="https://drive.google.com/file/d/1FDn_rz_exkyY_-8B0Z1UWIlE9XCxAkSu/view?usp=drive_link" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                border-2 border-solid border-transparent hover:border-dark
          "
          download={true}
                >Resume<LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:shuklasatyendu1538@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize text-dark underline "
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBulb} alt="Satyendu" className="w-full h-auto"/>
        </div>
      </main>
    </>
  );
}

