import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Satyendu Shukla</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
<Layout className="pt-0">
  <div className="flex items-center justify-between w-full">
<div className="w-1/2">
  <Image src={profilePic} alt="Satyendu" className="w-full h-auto"/>
</div>
<div>
  <h1>Crafting Dreams into Reality with Cutting-Edge Code and Design</h1>
  <p>As a passionate in data science and front-end development, I bring ideas to life through innovative web applications and data-driven solutions. Explore my projects and articles, showcasing my expertise in React.js, data science, and modern web development techniques.</p>
</div>
  </div>


</Layout>

      </main>
    </>
  );
}
